Makefile.libretro
This is NOT the cleanest way to do this, and I intend to revisit it later to see if I can improve upon it.  (How easy that will be depends on upstream support questions.)
For now what I've done is:
1. Override the default rule to be one that depends on all
2. Rename the output target to pcsx_rearmed_interpreter_libretro_ios.dylib on iOS when USE_DYNAREC is 0.
3. Our overridden rule cleans the project and reruns make with USE_DYNAREC=0 on iOS only.
This is actually a step backward for libretro-super, but it'll allow me to take two steps forward.
=> Generate dynarec AND interpreter on iOS (with single invocation!)

frontend/libretro.c, frontend/plugin.c, frontend/plugin_lib.h
Using two pads (xbox360 wireless clone) in analog mode:
pcsx_rearmed_pad1type = "analog"
pcsx_rearmed_pad2type = "analog"
Second controller analog input do not work. In Gran Turismo 2  second player
cannot use left analog joystick for steering. Proposed patch will enable
polling of second controller analog input when using libretro.
=> Poll analog inputs of pad2 when it's an analog pad.

frontend/libretro.c, frontend/menu.c, frontend/plugin.c, plugins/dfinput/main.c
Thanks for Retropie and all people involved. It is absolutely great to play Wipeout 2097 again after all these years. There is however one thing missing for the full experience, and that is playing with the neGcon steering wheel. For that I wrote (small) patch that enables neGcon controller functionality within Pcsx-Rearmed/Retropie. 
To get up-and-running is quite an adventure. The neGcon needs a USB Controller Adapter to connect with the Raspberry Pi. This adapter requires a special controller configuration file that translates the buttons and twist to the emulator. Finally, the correct Pad Type needs to be set in RGui so games are aware that a neGcon device is connected. (Rgui -> Quick Menu -> Core Options -> Pad 1 Type -> negcon)
The patch is working great. Games tested OK are Gran …
=> patch to support the neGcon racing controller

libpcsxcore/sio.c
This fix is borrowed from pcsxr. It adds neGcon compatibility for Wipeout3/SE and other games.
=> enhance neGcon compatibility

frontend/plugin_lib.c
Re: https://github.com/notaz/pcsx_rearmed/issues/64 (note this issue only effects the lib fork - these vars are not referenced upstream)
=> Fix undefined compile error

Makefile, Makefile.libretro
When compiling pcsx_rearmed with `make -f Makefile.libretro` both `DEBUG=1` and `DEBUG=0` will result in a debug build. This commit will make it so that `DEBUG=1` will result in `-O0 -ggdb -DOPENGL_DEBUG` while `DEBUG=0` and the default will be `-O2 -DNDEBUG` as it was before. Another change is that `-ggdb` will now only be used for debug builds where before it was used regardless.
=> Use DEBUG=1 properly for debug builds

Makefile
pcsx_rearmed is software only so `-DOPENGL_DEBUG` is not really needed...I'm not sure what I was thinking when I added it.
=> OPENGL_DEBUG is not needed

frontend/libretro.c
```
frontend/libretro.o: In function `retro_deinit':
libretro.c:(.text+0x3769): undefined reference to `deinit_vita_mmap'
collect2: error: ld returned 1 exit status
make: *** [pcsx_rearmed_libretro.so] Error 1
```
Introduced #68
=> Fix build error about undefined reference to `deinit_vita_mmap'

frontend/libretro.c
This fixes problems in games that expect the analog stick range to fall within the full [0, 255] range. In particular, Ape Escape requires that the -Y axis value of the left stick be exactly at 0 or the character can not run forward. Before this change, the axis value range only fell between [1,255].
=> Fixed analog stick ranges to be [0, 255]

Makefile.libretro, frontend/libretro.c, jni/Android.mk
This patch makes this core report the git version along with its library_version. This is important because otherwise it is impossible to replicate a build without extra knowledge, and things like Netplay that demand versions be the same can't be reliably known to work.
=> Report git version with library_version

frontend/plugin.c, frontend/plugin_lib.c, frontend/plugin_lib.h, libpcsxcore/plugins.c
After seeing the regressions from multitap I took a quick look at the
code, and there's quite a bit of cleanup needed.
This fixes the initial really obvious stuff, a useless copy and a
duplicate in_keystate that can cause compilation issues, along with
bringing styling closer to the pcsx standard so it's a bit more readable.
The multitap changeset also seems to have been done with an editor that
mangled line endings, I'll address that in a followup commit.
=> Do some light multitap cleanup

frontend/libretro.c
All non hexdec characters will be read as delimiters and reformatted for PCSX's preferred format, which means a space between code parts and newline between code lines.
Fixes #90
=> Enable support for multiline cheats.

libpcsxcore/cdriso.c, plugins/cdrcimg/cdrcimg.c
I am not sure if this is the best solution, but it works for me and probably at least could give an idea to a better solution.
This fixes https://github.com/libretro/pcsx_rearmed/issues/87.
=> Rename uncompress2 to avoid conflicts with zlib.h on some systems

frontend/libretro.c
Removes a hack breaking deserialization when running retro_reset(), retro_unserialize() and retro_run() in this order, as it silently resets the core just after setting its state.
I don't know how to properly fix the problem encountered in RA but silently reseting the core in retro_run() isn't the right solution as the core isn't reset after running retro_reset() and as it introduces other bugs.
=> libretro: Remove reset in retro_run() hack

frontend/libretro.c
This should allow one to disable vibration as a Core Option for LibRetro. 
Useful for PS3 controllers via on-board bluetooth on the RPi3. 
Will fix issue #56
https://github.com/libretro/pcsx_rearmed/issues/56
=> Adding "Enable Vibration" Core Option to LibRetro

frontend/libretro.c
The current message shown when there is no BIOS file doesn't make it clear that one can be added
=> More clear HLE BIOS error message

Makefile.libretro
To be honest, I have no idea of what I'm doing here.
This is a fix for #125. The increasing size of global variables in RetroArch codebase causes the BASE_ADDR to overlap with some of the variables, resulting in a crash.
I don't know if there's a reason why dynamic base is not used for 3ds. According to my tests everything seem to be working fine.
=> Use dynamic base address for 3ds

libpcsxcore/new_dynarec/backends/psx/emu_if.c
The dynarec was treating all gpu calls as flagless even when they where not because FLAGLESS was not undefined after including gte.h
Should fix #135 #103
=> Fix polygon issues

Makefile.libretro
- this allows PCSX Rearmed to build on Haiku (tested working)
- also fixes the uname being too broad for Solaris as suggested by @bparker06
=> Fixed uname for Solaris + enabled Haiku build

frontend/menu.c
Default to 100% CPU speed as most hardware can handle it nowadays using the dynamic recompiler. 
If not, the option is in the advanced speed hacks menu, so in a logical place.
=> Changed default clock speed to 100% from 57% in non-lr build

frontend/libretro.c
Use proper slash or backslash
search for lowercased filenames for supported bios files too
=> Fix core not finding bios file

frontend/libretro.c
Zero-copy (software) buffers must not be re-used.
From the API:
> The framebuffer [...] must not be used after the current call to retro_run() returns.
=> Fix zero-copy (software) buffer

frontend/libretro.c, frontend/libretro.h
While the core nominally supports virtual negCon devices, the current implementation is broken and unusable. This pull request just remaps negCon input to match the setup in the beetle-psx core, as follows:
Digital input:
- negCon d-pad: RetroPad d-pad
- negCon Start: RetroPad Start
- neGcon A: RetroPad A
- neGcon B: RetroPad X
- neGcon R shoulder: RetroPad R
Analog input:
- neGcon twist: RetroPad left analog (x-axis)
- neGcon I: RetroPad R2 or B
- neGcon II: RetroPad L2 or Y
- neGcon L shoulder: RetroPad L
As with the beetle-psx core, the analog inputs make use of the RetroArch 'analog button' feature - so most modern gamepads should allow for 'proper' analog acceleration/breaking (in racing games) via the right/left triggers.
=> Fix negCon input mapping

frontend/libretro.c
Hi. I was frustrated that memcard2 was not supported, so I decided to hack into the code.
I've been playing for a day and cleared a game where I needed two memory cards without issue.
Are you for/against this change?
- The memcard2 is automatically set to a file named `pcsx-card2.mcd` in the folder of the loaded game. Maybe we should make that configurable? If so, how?
=> Support memcard2

frontend/libretro.c, frontend/plugin.c, frontend/plugin_lib.c
analog pad type now corresponds to the spch-1110 analog joystick or spch-1150 in flightstick mode.
the new pad type dualshock was added to the menu that corresponds to the old analog pad type spch-1200.
this will solve #198
=> enabled scph-1110 analog joystick in the menu

frontend/libretro.c
closes https://github.com/libretro/pcsx_rearmed/issues/219#issuecomment-458348900
=> Hide nonfunctional NEON options in aarch64

libpcsxcore/cdriso.c
Fixes https://github.com/libretro/pcsx_rearmed/issues/63
I tested without issues:
* Loading content with relative paths (`foo/bar.cue`, `./bar.cue` and `bar.cue`)
* Loading content with absolute paths.
* Loading content from the menu with `Load Content`.
* Loading content from the menu with a playlist.
Before this it would fail with relative paths like `./bar.cue` or segfault with `bar.cue`.
=> Fix segfault when loading cue files from relative paths.

Makefile.libretro, frontend/libretro.c, libpcsxcore/misc.c, libpcsxcore/psxcommon.h
958c981 Fix CD audio not playing on some platforms 
- related post https://github.com/libretro/pcsx_rearmed/issues/224
- this needs verification as to which platforms supports -lm for linking
79f29e0 Fix detection for rumble interface
- rumble interface is always assumed is available, causing it to crash when rumble core option is left to enabled (default). This detects if rumble interface is available before sending rumble states.
0963774  Run SysReset() only from retro_run, causes retroarch to freeze...
- SysReset() crashes when loading with a real bios file if it is not called from retro_run(). This is already known based on an already added workaround from previous commit. This moves SysReset() from retro_load_game() to retro_run(). Can't figure out the "why" this happens though and …
=> Core fixes

Makefile.libretro
reverts https://github.com/libretro/pcsx_rearmed/commit/5d705e23cff70876ca4ac0e8f0a357f4edfd9fd6
related : https://github.com/libretro/pcsx_rearmed/issues/188
=> 3DS: Restore default gpu

Makefile.libretro, jni/Android.mk, plugins/gpu_unai/gpu_arm.S, plugins/gpu_unai/gpulib_if.cpp
- gpulib_if.cpp: fix some -fpermissive issues during build
- renamed gpu_unai/gpu_arm.s to gpu_arm.S and added necessary header
- update Android.mk for unai (used in armeabi)
- re-enabled unai or 3DS
reference post : https://github.com/libretro/pcsx_rearmed/issues/188
=> gpu_unai buildfix and re-enable on 3ds

frontend/libretro.c
This reverts commit https://github.com/libretro/pcsx_rearmed/commit/0963774720493115d123104f9ddc506d49a886bc, which was added to remedy issue on ludo when using official bios. turns out if has affected HLE on arm. Other arm users so far don't have issue with this PR nor they gained any advantage over it so issue probably is just ludo exclusive. 
Reverting this.
=> Reverts 0963774 (Run SysRese) only from...)

plugins/gpu_unai/gpulib_if.cpp
on CTR(3DS) compiling the core using **make platform=ctr** or **libretro-build-ctr.sh pcsx_rearmed** successfully creates pcsx_rearmed_libretro_ctr.a file.
When creating core with retroarch using **<retroarch-repo>/dists-scripts/dist-cores.sh ctr**, it fails to create a .3dsx or .cia files for both retroarch and pcsx_rearmed core showing this error:
```
/opt/devkitpro/devkitARM/bin/arm-none-eabi-g++ -specs=ctr/3dsx_custom.specs -g -march=armv6k -mtune=mpcore -mfloat-abi=hard -marm -mfpu=vfp -mtp=soft -Wl,-Map,.map  gfx/drivers/ctr_shaders/ctr_sprite.o ctr/ctr_system.o ctr/ctr_memory.o ctr/ctr_linear.o ctr/gpu_old.o ctr/exec-3dsx/exec_cia.o ctr/exec-3dsx/exec_3dsx.o ctr/exec-3dsx/mini-hb-menu/launch.o ctr/exec-3dsx/mini-hb-menu/loaders/rosalina.o ctr/exec-3dsx/mini-hb-menu/loaders/hax2.o …
```
=> GPU unai update

Makefile.libretro
* Default to `HAVE_NEON=0` until the `platform` is checked for `neon`
* Fixes build with `platform=armv` alone (no NEON requested) in a NEON device where the autodetection using `$(CC) -E -dD` will enable it
This happens in a chroot cross-compile environment such as in the RetroPie binary builder.
Edit: this shouldn't affect any other platform/condition, including the buildbot.
=> (BuildFix) Do not leave HAVE_NEON unset in armv platform check

frontend/libretro.c
- When **Show Bios Bootlogo** hack is enabled, logo only shows during reset but not during loading game.
Fix https://github.com/libretro/pcsx_rearmed/issues/257
=> Fix bootlogo showing only during reset when enabled

libpcsxcore/plugins.c
Reverts libretro/pcsx_rearmed#262
this is incorrect. causes missing rumble and KoroKoro does not support analog.
newer PR will be sent soon unless someone beats me to it.
reopen the related bounty source post for this: https://github.com/libretro/pcsx_rearmed/issues/161
=> Revert "Fix input not working in some games"

Makefile.libretro
Large file support is not enabled in `Makefile.libretro`, therefore when loading large PBP files you might get "Value too large" errors in some 32-bits systems (e.g. Raspberry Pi), like this:
Could't open '/home/pi/RetroPie/roms/psx/Final Fantasy VIII (USA).pbp' for reading: Value too large for defined data type
Error opening CD-ROM plugin!
This was recently reported in the [RetroPie forum by a number of users](https://retropie.org.uk/forum/topic/21852/psx-value-too-large-to-launch-after-update/). I now also confirmed the issue on my RPI 3B+ aswell with a large Final Fantasy VIII PBP file (2212574811 bytes). This was not happening before but seems to be recently introduced by the embedded zlib dependency.
The solution in this PR backports the same feature check from the `configure` script …
=> Backport large file support from configure script and improve makefile

Makefile.libretro
The recompiler can't handle Thumb instructions, so they must be disabled.
This is accomplished via the `-marm` flag being set for different platforms.
However, when using `platform=unix` and manually configuring the build, the check for Thumb instructions is not done in `Makefile.libretro`. Therefore, when building with a compiler that defaults to Thumb instructions (e.g. ODROID-XU4), the build can fail with this error:
libpcsxcore/new_dynarec/backends/psx/pcsxmem.c:18:2: error:
#error the dynarec is incompatible with Thumb functions,
libpcsxcore/new_dynarec/backends/psx/pcsxmem.c:19:2: error:
#error please add -marm to compile flags
To address this, we simply backport the define check from the configure script for when we build with `ARCH=arm`. This change doesn't affect the buildbot. …
=> Backport check for Thumb instructions from configure script

Makefile, Makefile.libretro, libpcsxcore/cdriso.c
- all platforms compiles with CHD support.
- compile with HAVE_CHD=0 for no chd support.
- CHD fails building for 3DS, not sure its even fast enough for the device. I tried asking in discord channel but haven't got reply. Disabling it till someone familiar with 3ds can fix it.
http://p.0bl.net/123458
=> Allow building without CHD, disable CHD for 3DS

Makefile
buildbot log http://p.0bl.net/123526
```
cc  -DGIT_VERSION=\"" 4b7520c"\" -D__WIN32__ -DNO_DYLIB  -D_FILE_OFFSET_BITS=64 -Wall -Iinclude -ffast-math -O2 -DNDEBUG -Ideps/zlib -Ideps/libchdr -Ideps/crypto -Ideps/flac-1.3.2/include -Ideps/flac-1.3.2/src/libFLAC/include -Ideps/flac-1.3.2/src/libFLAC/include -Ideps/lzma-16.04/C -D'PACKAGE_VERSION="1.3.2"' -DFLAC__HAS_OGG=0 -DFLAC__NO_DLL -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DFLAC__NO_DLL -D_7ZIP_ST -DFRONTEND_SUPPORTS_RGB565 -DHAVE_LIBRETRO -DNO_FRONTEND -c -o deps/flac-1.3.2/src/libFLAC/bitmath.o deps/flac-1.3.2/src/libFLAC/bitmath.c
In file included from deps/flac-1.3.2/src/libFLAC/include/private/bitmath.h:39,
from deps/flac-1.3.2/src/libFLAC/bitmath.c:37:
deps/flac-1.3.2/include/share/compat.h:57:16: error: conflicting types for …
```
=> Fix CHD build for windows

frontend/libretro.c
- advance options > Disable XA Decoding, Disable CD Audio
- dynarec speedhacks > Disable SMC checks, Assume GTE regs unneeded, Disable GTE Flags
reference: https://github.com/libretro/pcsx_rearmed/issues/294
=> Add core options for some advance settings and dynarec speed hacks

frontend/libretro.c
This change allows dynamically switching resolutions when using CRT monitors.
=> Report correct geometry and update geometry when needed

frontend/libretro.c
When the bitmask input code was added, a little typo broke dpad up when using neGcon input devices.
This trivial PR fixes the issue.
=> Fix neGcon input

Makefile, libpcsxcore/psxhle.c
- at least one game (Wild Arms) is continouosly spamming the log window. Silence this in a way that its easy to enable when need to.
- Remove unnecessary message in Makefile
=> psxhle.c: Silence logging when using HLE bios

frontend/libretro.c
PSX Main RAM should only by 2048KB
=> Fix main RAM size in retro_get_memory_size

frontend/libretro.c, frontend/libretro_core_options.h
- give a more human-readable key labels for advanced gpu options
- close plugins when exiting core
=> Sanitize gpu adv options and close plugins upon exiting core

configure
- This is meant for platforms that still uses the non-static build method to compile the libretro core (aka versions of retropie)
- The output file is still libretro.so to preserve any compatibility with existing script
- Using the static makefile is still recommended.
reference: https://github.com/libretro/pcsx_rearmed/issues/329
=> Do not compile plugins when using the non-static build method

frontend/libretro.c
This allows you to use the PSXONPSP660.bin "optimized" PSP PSX BIOS that is being circulated online. See https://forums.libretro.com/t/psx-bios-from-psp-6-60-optimised-to-play-games-more-smoothly-but-how and libretro/beetle-psx-libretro#519
I don't know if there's any particular naming convention to this BIOS, so I have additionally added psx* to search in find_any_bios(). It shouldn't really be called scph*, though, since the BIOS is not from actual playstation hardware.
=> Added support for PSXONPSP660.bin and psx* named BIOS files

frontend/main.c
With iTempo turned on, we generate a frame and a half of sound data each frame, which causes dropped sound frames and noise.
It looks like GPH hacks are disabled for 3ds in other places, so disabling it here too seemed like the correct fix.
=> Fix sound over-buffering on 3ds

Makefile.libretro
I don't know what build errors were happening before, but this built cleanly for me. I tested on a few CHDs and it loads them just fine -- in fact, it seems like they run much faster than bin/cue. I couldn't get m3us referencing CHDs to load, though -- is that expected?
=> Enable CHD on 3DS builds

deps/flac-1.3.2/src/libFLAC/metadata_iterators.c, deps/flac-1.3.2/src/share/grabbag/file.c
The toolchain doesn't have utime defined, so these calls will fail.
=> Stop calling utime on 3ds

frontend/3ds/pthread.h
When creating a thread, pcsx was scheduling threads on core 1, which is the system core. This is usually prevented by the system. Instead, it should schedule threads on the default core, as suggested by 3dbrew: https://www.3dbrew.org/wiki/Multi-threading
> Games usually create threads using -2.
In the future, we may be able to schedule threads on core 2 on New 3DS only, if we find it gives better performance.
This was preventing the CDDA thread from starting, which was preventing CD Audio from playing.
=> 3DS: Schedule threads on the default core

frontend/3ds/3ds_utils.h, frontend/3ds/pthread.h
This fixes some arm11 exceptions/crashes that came up once threading was re-enabled by #353.
svcCreateThread doesn't fully set up thread vars, which causes svcBreaks / crashes when calling certain functions -- reentrant ones, for example. threadCreate, etc. are higher-level functions that do all the correct setup and cleanup.
Since we're treating the thread structure as opaque, continuing to call it an int_32t seems OK.
=> 3DS: Switch from svc* to the thread* API

libpcsxcore/cdriso.c
same syntax as beetle-psx, name the sbi file after the pbp and append an underscore and the number of the disc at the end.
example:
"Final Fantasy IX (EUR).pbp"
"Final Fantasy IX (EUR)_1.sbi"
"Final Fantasy IX (EUR)_2.sbi"
"Final Fantasy IX (EUR)_3.sbi"
"Final Fantasy IX (EUR)_4.sbi"
=> sbi support for multidisc pbp

frontend/libretro.c, frontend/libretro_core_options.h
Adds the "Spu Irq" advance options to core menu.
Fix https://github.com/libretro/pcsx_rearmed/issues/359
=> Add "Spu Irq" core option

frontend/libretro.c
attemp to fix this using memory_map instead: https://github.com/libretro/pcsx_rearmed/issues/367
If it does not fix it, it wont do harm anyways.
=> Access psx main memory using retro_memory_map

frontend/libretro.c, libretro-common/include/libretro.h
This PR adds full support for libretro disk control interface v1. This includes the following enhancements:
- Disk names are now shown when swapping disks via the `Current Disk Index` drop down list
- When loading multi-disk content (M3U playlists or PBP files), the last used disk index is now automatically saved/restored
=> Add disk control interface v1 support

frontend/libretro.c, frontend/libretro_core_options.h
Add core option to change axis saturation. Square bounds allow controllers that struggle to fully register diagonal deflections . Very helpful with switch joycons and some android controllers.
=> Add input analog axis range modifier

libpcsxcore/lightrec/plugin.c, libpcsxcore/psxmem.c
Also prefer MAP_FIXED_NOREPLACE over MAP_FIXED, as it won't remove old memory maps
Fixes #382 
Tested to work on both Windows 10 64-bit and Linux
=> Fix second instance runahead

Makefile.libretro, frontend/3ds/3ds_utils.h, frontend/3ds/utils.S, libpcsxcore/new_dynarec/new_dynarec.c
After the dynarec writes new instructions, it has to flush the instruction and data caches. Some of these flush operations are privileged on the 3DS, so the clear cache functions have to run
through svcBackdoor. The Nintendo implementation (and CFW reimplementation) of svcBackdoor has a problem where interrupts and context switches will cause crashes. See [here](https://github.com/AuroraWright/Luma3DS/blob/master/k11_extension/source/svc/Backdoor.s#L39) for a note on this.
Even though we can disable interrupts in the flush function, there's a window of time between svcBackdoor being called and the function being run where an interrupt will corrupt the stack. Most of the time, svcBackdoor is just used for setup, so this isn't a problem. But the dynarec can call this function many times per …
=> Fix dynarec crashes on 3DS

Makefile, Makefile.libretro
Adjusting a few things in the makefile to get some easy performance boosts. 
I did some measurement with Crash idling on the beach he starts on in Crash 1. All of these together brought it from ~44.5 fps to ~50.9.
I tried all four unai options, this was the fastest by ~0.5fps.
=> [3DS] Tweak compile-time options to increase performance

Makefile, frontend/3ds/3ds_utils.h, frontend/3ds/pthread.h, frontend/libretro.c, frontend/libretro_core_options.h, libpcsxcore/cdriso.c, libpcsxcore/psxcommon.h
This adds an option for asynchronous CD reads that acts like the one in Beetle PSX. When you turn it on:
- Data CD reads happen in a background thread
- The thread will try to prefetch the next few sectors when it's not fulfilling a request
- The thread will keep some data in a memory buffer, so it can quickly serve fetched data if it still exists
I've been running this on my 3DS for a week or so without issue. I haven't tested it on any other platform, but it should be possible to make it work on platforms that support pthreads. Right now I have it behind `!defined _WIN32`, since that's what controls other threading stuff in the core. But it might be better to have a specific flag for it.
I would like some more testing on this before it's merged, because I've only tried it on a limited …
=> Add an async CD access method

plugins/gpu_unai/gpu_inner.h, plugins/gpu_unai/gpu_inner_blend.h, plugins/gpu_unai/gpu_inner_blend_arm.h, plugins/gpu_unai/gpu_inner_light.h, plugins/gpu_unai/gpu_inner_light_arm.h
Looking at the generated ASM on 3ds, I thought I could squeeze out some extra performance by moving the inner lighting and blending functions to handwritten A32 assembly. This branch gives a medium improvement generally (3-5fps faster on the beach in Crash 1) and a large improvement when doing lots of blending (46-48fps before, 57-60fps after, behind the waterfall in Water Dragon Isle in Chrono Cross).
I still have some cleanup and documentation I want to do before this is ready to merge, but wanted to open this for comment.
Some other notes: 
- I used the ARM11 MPCore (3DS CPU) timings for pipelining. 
- I had a few stall cycles during lighting, so I used them to preserve the MSB for lighting and blending, which saved a store, load, and `orr` later on. ~3-6 cycles saved overall by doing …
=> unai: Add ARM-optimized lighting / blending functions

frontend/cspace_neon.S
Recently got a Raspberry Pi 4, and installed RetroPie on it. Loaded up FF7 via the PCSX ReARMed core and immediately noticed some of the objects on screen had off-black backgrounds (such that I could easily tell the geometry of the object).
Squaresoft logo:
Main menu:
Staring at those screens long enough, you'll start to notice the off-black is actually some dark shade of green. 
After many hours, I tracked down the problem to cspace_neon.S - specifically the bgr555_to_rgb565 function. Neither the C or ARM versions had this issue when the core was built with those instead. Turns out the neon version of bgr555_to_rgb565 wasn't discarding the MSB of the BGR color (used for transparency / masking elsewhere in the PSX) and as a result, the bit twiddling operations end up corrupting the green …
=> neon: Fixed bug where MSB of a 15-bit BGR color could corrupt green value.

libpcsxcore/cdriso.c
A few RetroPie users reported that disk switching freezes/crashes RetroArch, either doing the switch from a playlist (`.m3u`) or by appending a new disk image (no playlist).
I bisected the issue to the CD Async read  commit https://github.com/libretro/pcsx_rearmed/commit/8fda5dd0e28fe46621fb1ab57781c316143017da by @justinweiss. This can be worked around by choosing the `async` CD Read method in the core options, but `sync` is the default.
The change just adds a guard around `readThreadStop` - similar to how t's done to `readThreadStart` - and prevents the crash/deadlock.
=> cdriso: fix a disk switching deadlock when closing a CD image

frontend/libretro.c
Fixes https://github.com/libretro/pcsx_rearmed/issues/404
=> Automatically disable lightrec when no bios is present

frontend/libretro.c
Make sure to only do it with lightrec and not ARM dynarec.
Fixes https://github.com/libretro/pcsx_rearmed/issues/409
=> Automatically disable lightrec when no bios is present, take 2

frontend/libretro.c
- Core sometime freeze while loading content during the loading of the core options. Moving update_variables() from retro_init to retro_load_game() fixes the problem, on my case at least.
- Also apply fix as suggested in this issue page: https://github.com/libretro/pcsx_rearmed/issues/373
=> Fix some edge case where core can freeze upon loading content

frontend/libretro.c
- Using retro_memory_descriptors[] for memmap creates a list of address for a game. At the moment, its quite long and can cover up the log window.
Since there is only 1 pointer used, using the traditional retro_get_memory_map/data works enough for this purpose.
- Move the use of memory descriptors to debug build.
=> Minimize logs when loading a cheevos-compatible content

Makefile, deps/lightrec/.gitrepo, deps/lightrec/CMakeLists.txt, deps/lightrec/README, deps/lightrec/README.md, deps/lightrec/blockcache.c, deps/lightrec/blockcache.h, deps/lightrec/config.h, deps/lightrec/debug.h, deps/lightrec/disassembler.h, deps/lightrec/emitter.c, deps/lightrec/emitter.h, deps/lightrec/interpreter.c, deps/lightrec/interpreter.h, deps/lightrec/lightrec-private.h, deps/lightrec/lightrec.c, deps/lightrec/lightrec.h, deps/lightrec/memmanager.h, deps/lightrec/optimizer.c, deps/lightrec/optimizer.h, deps/lightrec/reaper.c, deps/lightrec/reaper.h, deps/lightrec/recompiler.c, deps/lightrec/recompiler.h, deps/lightrec/regcache.h, deps/lightrec/slist.h, libpcsxcore/lightrec/plugin.c
This updates lightrec dependencies and plugins to latest upstream.
This does not fix the issue related to shutdown/reset though, just meant to make it upstreamed.
Needs review if there are any lingering issues doing this on pcsx.
=> Update lightrec to latest upstream

frontend/libretro.c
- For systems that can only run in interpreter mode for whatever reasons.
Fix: https://github.com/libretro/pcsx_rearmed/issues/408
=> Fix interpreter-only build (DYNAREC=0)

frontend/libretro.c, libretro-common/include/libretro.h
This PR adds support for the 'extended' frontend message interface implemented here: https://github.com/libretro/RetroArch/pull/10679
The main benefit is that enabling the display of internal FPS no longer spams the log with useless messages.
@negativeExponent I think this is what you wanted...?
=> Add support for frontend message interface v1

frontend/libretro_core_options.h
- Setting this option enabled can cause graphics issues.
See ground polygons:
=> change fast lighting default to disabled

libpcsxcore/cdrom.c
Fixed bug where MSB of a 15-bit BGR color could corrupt green value. Also added documentation.
92db770
Fix crash on retrying mission in driver (notaz#165)
fbf19ce
=> sync to latest upstream

frontend/libretro.c, frontend/libretro_core_options.h, frontend/main.c, frontend/menu.c, frontend/plugin_lib.h, plugins/gpu_unai/gpu.h, plugins/gpu_unai/gpu_unai.h, plugins/gpu_unai/gpulib_if.cpp, plugins/gpulib/gpu.h, plugins/gpulib/vout_pl.c
Some older devices that use gpu_unai don't have a high enough resolution to display all of the pixels in high-res mode. There's a setting in unai to skip rendering of these pixels, but it's not connected to the libretro frontend, and does not appear to be used in the gpulib implementation at all.
This commit adds a gpu_unai setting, Enable Hi-Res Downscaling, that will enable unai's pixel skipping and blit only the pixels actually rendered into a buffer no larger than 384x240. This buffer is then treated as the actual framebuffer by gpulib and the libretro frontend.
=> Add an option to downscale hi-res views

Makefile.libretro, frontend/3ds/3ds_utils.h, frontend/3ds/pthread.h
Similar to https://github.com/libretro/FFmpeg/pull/11 and https://github.com/libretro/ThePowderToy/pull/6, this needed a pthreads implementation that was compatible with both the old libretro-toolchains toolchain and the newest devkitARM toolchain. I used the same strategy here, although I didn't see it complain about the casts.
This also needed `-fcommon` to avoid duplicate definition errors under GCC 10.
Finally, I switched to using the 3ds.h header instead of the inline definitions, in order to avoid inconsistencies.
This successfully builds under both the version of devkitARM in libretro-toolchains and the newest devkitARM.
=> [3DS] Support latest libctru

frontend/libretro.c
Adjust existing code to allow for multiple guncon devices. Previously hardcoded to port 1 because of past RetroArch bug.
Tested with Point Blank, seems to work.
Hope this suits, but let me know if any change is required.
=> Add support for dual-guncon

libpcsxcore/cdriso.c
Previously, when an access went out of bounds, we would stop reading ahead, but not add the error flag to the correct place in the sector buffer. This could hang the main thread as it waited for a read result that would never come.
=> Correctly signal errors for out-of-bounds async CD reads

Makefile.libretro, frontend/3ds/3ds_utils.h, frontend/3ds/pthread.h, frontend/3ds/semaphore.h
SPU threading is enabled automatically when `THREAD_ENABLED` is set. It requires semaphore.h, so a simple wrapper implementation was added. This PR also replaces the 3DS pthread wrapper with one based on the libretro-common version.
=> [3DS] Enable threading for the SPU

libpcsxcore/psxcounters.c, libpcsxcore/psxcounters.h, libpcsxcore/r3000a.c
...was testing this over the weekend and had to apply these fixes for it to work on the raspberry pi platform. Audio is still missing but that might be related with something else.
=> fixes link time errors on the RPi platform (tested with 3 and 4)

libpcsxcore/psxcounters.c, libpcsxcore/psxcounters.h, libpcsxcore/r3000a.c
Reverts libretro/pcsx_rearmed#458
=> Revert "fixes link time errors on the RPi platform (tested with 3 and 4)"

frontend/libretro.c, frontend/libretro_core_options.h
3DS handles it fine, and 50 makes Metal Gear Solid feel very sluggish.
=> [3DS] Set default CPU rate to the usual 57

Makefile, Makefile.libretro, frontend/libretro.c, frontend/libretro_core_options.h, frontend/main.c, frontend/menu.c, frontend/plugin_lib.h, plugins/dfxvideo/gpulib_if.c, plugins/gpu-gles/gpulib_if.c, plugins/gpu_neon/psx_gpu_if.c, plugins/gpu_unai/gpulib_if.cpp, plugins/gpulib/gpu.c, plugins/gpulib/gpu.h, plugins/gpulib/gpulib_thread_if.c, plugins/gpulib/gpulib_thread_if.h
This change adds a stub gpulib implementation that accepts GPU commands and runs them through a real gpulib implementation running on a thread.
The threaded renderer can run in three modes.
In the "off" mode, the renderer will simply hand commands off to the real gpulib implementation, without using a thread.
In the "sync" mode, the renderer will run during a frame, and will block if any GPU commands are still active when the frame needs to render.
In the "async" mode, the renderer uses a heuristic to detect when it should block, and allows the renderer to continue running otherwise.
For games that naturally run at less than 50/60fps, syncing every frame is unnecessary -- it forces the game to render as if it was 60fps and leaves the GPU idle half the time on a 30fps game, for example. …
=> Add a threaded renderer

Makefile.libretro
By default, iOS are built with either DYNAREC=ari64 or DYNAREC=lightrec, with lightrec used as an override flag to build the interpreter instead, which is DYNAREC=0.
This PR removes DYNAREC?=ari64 which seems to block the overrides from working.
Hopefully...:
=> iOS: Fix interpreter overrides

Makefile, Makefile.libretro, frontend/libretro_core_options.h, plugins/dfxvideo/gpulib_if.c, plugins/gpulib/gpulib_thread_if.c
This allows peops to use threaded rendering, and shows the setting on unix builds (this was the only other platform I have on hand to test). Enabling the setting on other pthread-compatible platforms using either unai or peops should be as simple as defining `THREAD_RENDERING` in the Makefile. 
A change similar to this one should work with gpu_neon, but I don't have any neon devices on hand to check with. Should be straightforward if someone wants to try.
=> Allow threaded rendering for peops and enable on unix

Makefile.libretro, libpcsxcore/psxcounters.c, libpcsxcore/r3000a.c
Affects builds that uses ari64 (DYNAREC=ari64). Two variables, rcnt and psxRegs causes these platform to fail on gcc10.
This PR blocks the stated variables with #ifdef when building with ari64, and use the definition for the vars from **libpcsxcore/new_dynarec/arm/linkage_arm.S** instead to avoid the multiple definition errors when linking.
I have not personally tested the core to run, only compilation and linking with RA.
for review @twinaphex @@justinweiss @dmorilha
=> Fix build with -fno-common (default in gcc10)

frontend/libretro_core_options.h
Due to moving input selector to frontend instead from the core options,
ports 3-8 can be always set to standard causing multitap to be auto-activated.
With multitaps enabled, some games would misbehave or inputs not working
at all for those that are not multiplayer capable.
Setting core option multitap1 and multitap2 to disable for now.
=> Set multitap options to "disabled" by default

frontend/libretro.c, frontend/libretro_core_options.h
Prevents multitap core option to be accidentally set to auto due to loading previous core option defaults...
=> multitap option fix

frontend/libretro.c
At the moment, if you have "hle" BIOS selected in core options it will show a "no PlayStation BIOS found" message, even if you have a BIOS file in your system folder. It seems to confuse some people, so I think it would be nice to have a different message displaying in this case.
It's a really simple PR but I'm not a dev (I just have some bash scripting knowledge... 😅 ), so I'm "afraid" to break something, the logic itself works fine, but I'm not sure about a few things:
1. The message itself, does it make sense to you? Kinda hard to make something clear while keeping it short. But it hints the user at checking the core options and it clearly states that if you have a real BIOS it won't be used.
2. I escaped the `'` in the message itself to be safe but I'm not sure if needed or completely …
=> Change HLE BIOS message. Please review first!

Makefile
Threaded rendering is only supported with unai and peops, so the define should only be set if one of those drivers are selected.
Fixes #494
=> Restrict threaded rendering to unai / peops

Makefile, frontend/libretro.c, libpcsxcore/cdriso.c, libpcsxcore/psxmem.c, libpcsxcore/sio.c, libretro-common/compat/fopen_utf8.c, libretro-common/encodings/compat_strl.c, libretro-common/encodings/encoding_utf.c, libretro-common/include/boolean.h, libretro-common/include/compat/fopen_utf8.h, libretro-common/include/compat/strl.h, libretro-common/include/encodings/utf.h, libretro-common/include/libretro.h, libretro-common/include/retro_common_api.h, plugins/cdrcimg/cdrcimg.c
This selectively replace fopen calls with fopen_utf8, to handle paths
that uses special characters in Windows.
The replacement covers these:
- opening of bios file
- opening, writting and creating memcard2
- opening and handling of disk images
Related: https://github.com/libretro/libretro-fceumm/issues/448
=> Selectively replace fopen() with fopen_utf8()

deps/libchdr/include/libchdr/coretypes.h
RE: https://github.com/libretro/libretro-fceumm/issues/448
Minimal change to fix/resolve issues opening CHD files from paths with special character names
=> libchdr: Use also fopen_utf8 here

Makefile, libpcsxcore/psxinterpreter.c, libpcsxcore/psxmem.c
- Reduces binary to about half the size
- These are mostly breakpoints anyways, which atm there is no way to interface with frontend for debugger needs.
- Compile with DEBUG=1 to build core with debug code
=> Do not compile debugger codes by default

deps/lightrec/interpreter.c, libpcsxcore/psxinterpreter.c
This PR handles an undocumented edge case of division overflow in the DIV instruction both in lightrec and the interpreter. Without this patch, guest code will get unexpected results, and may even crash the core on x86, as AmiDog's basic CPU test shows.
=> Handle DIV overflow in lightrec and the interpreter

frontend/libretro.c
Frontends that do not support RETRO_ENVIRONMENT_GET_VARIABLE (like
miniretro & nanoarch) cause a segfault in the CPU emulation path unless
the BIOS file is present. This is due to the emulator not supporting
running without a BIOS in dynarec mode and the code not being able to
swap CPU types (unless the callback returns true).
=> Fix initialization on Frontends without variable support.

libpcsxcore/cdrom.c, libpcsxcore/cdrom.h
Upstreamed changes from PCSX Redux as seen here :
https://github.com/grumpycoders/pcsx-redux/commit/5730e04f0183f37038bc1d133cf9f9092425b90a
This apparently fixes Deus Fight in Xenogears and it was reported to fix the freeze after Lunar Cry FMV in Final Fantasy 8.
(It also seemingly fixed the desync issue in CTR's intro although i'm not sure if it was that fix or https://github.com/notaz/pcsx_rearmed/pull/183)
I have not noticed any regressions so far (and the redux project has not it seems either) but feel free to test.
=> CDRom timings changes

Makefile, deps/libchdr/include/libchdr/coretypes.h, deps/lightning/lib/jit_print.c, deps/lightrec/emitter.c, frontend/libretro.c, libpcsxcore/cdriso.c, libpcsxcore/disr3000a.c, libpcsxcore/lightrec/plugin.c, libpcsxcore/misc.c, libpcsxcore/ppf.c, libpcsxcore/psxinterpreter.c, libpcsxcore/psxmem.c, libpcsxcore/sio.c, plugins/dfsound/out.c
PCSX spams a lot of warnings while it's built using GCC, and they are very distracting during development. This PR removes all of them, the hard way: IO warnings (most of them about unchecked freads) by adding extra checks, printf overflow warnings by switching to snprintf, unused functions and variables warnings by disabling those for the deps folder, and others mostly by initializing vars in undecidable functions and by fixing minor bugs. Only a single warning indicated a bug - that one I marked with a TODO for later.
Some extras included:
- A pair of stray debug printfs were removed, one in lightrec, the other in dfxsound.
- Debug builds previously failing because of name conflicts between debug functions and their stubs are restored.
- IO errors are now reported using OSD messages in …
=> Sort out compiler warnings, all of them

libpcsxcore/cdrom.h
Notaz pointed that to me that the way i put my variable inside the structure broke save state compatibility. https://github.com/notaz/pcsx_rearmed/pull/184#pullrequestreview-731139926
He suggested using one of the pad members instead, which i have just done instead.
I'll probably wait for him to confirm if it's good but i think it's the right way.
=> Fix save state compatibility that was broken by my CDrom timing changes.

libpcsxcore/gte.c, libpcsxcore/gte_divider.h
This came from jdgleaver/RG350_pcsx4all@864de67
Original comment by senquack :
"gteH register is u16, not s16. DIVIDE macro/func assumed it was
s16 for some reason. Behavior now matches Mednafen."
I'm surprised this wasn't merged back yet and it seems correct.
I also put in there the "GTE_USE_NATIVE_DIVIDE" stuff but currently unless manually enabled, it's not used.
You may wish to use this on some low end platforms but that's up to you.
Fix was merged by notaz (See https://github.com/notaz/pcsx_rearmed/pull/185)
=> gte: Fix gteH division and sign extension (from PCSX4ALL)

plugins/dfsound/registers.c
Fix is from PCSX-Redux :
grumpycoders/pcsx-redux@4e905d7
I have tested the fix against Loonies 8192 (a PSn00bSDK made homebrew game) and it no longer locks up during loading.
This affects all games and demos that uses PSn00bSDK. (I've been told it's unlikely this will affect games that uses the official SDK)
Said PR was also merged by Notaz (See https://github.com/notaz/pcsx_rearmed/pull/190) so it's all good.
=> [SPU] Emulate SPUSTAT[5:0] as a mirror of SPUCNT[5:0]

libpcsxcore/mdec.c
This based on an original fix by dmitrysmagin in PCSX4ALL.
He had this to say :
"This fixes graphic artifacts during cinematics in Vandal Hearts
and R-Types, other games seem to be unaffected. (?)
Need to test more, revert if problems."
I can confirm for me this fixes the graphical issues that happened during the videos in R-types.
People that used the PCSX4ALL fork that used this fix for a while did not seem to have encountered any regressions.
Setting it to 4 still doesn't fix the problem, it needs to be 6.
**Below : MDEC_BIAS set to 2**
**Below : MDEC_BIAS set to 6**
However, it turns out MDEC_BIAS set to 6 was still not enough for Galerians.
As said in https://github.com/notaz/pcsx_rearmed/issues/145, Galerians has the same issue but worse.
Setting to 6 makes it look like this
That …
=> mdec.cpp: Dare to set MDEC_BIAS to 10

libpcsxcore/psxbios.c
See PCSX-Redux :
https://github.com/grumpycoders/pcsx-redux/blob/93653ba5281487d3bed57371d7b64c32dfc669f0/src/mips/openbios/gpu/gpu.c
That +1 was killing me... but the reason why it exists at all was because it was based upon the decompilation by a Japanese user of the PS1 bios.
Pointer for GPU_dw is also u32, according to OpenBIOS.
This was approved by notaz (See here : https://github.com/notaz/pcsx_rearmed/pull/192)
=> Rewrite GPU bios functions according to OpenBIOS.

libpcsxcore/cdrom.c
This was inspired by the fix in Duckstation :
https://github.com/stenzek/duckstation/commit/0710e3b6d384526ed939f742f8f657623bb354bb
Some games have junk audio sectors with a channel number of 255.
If these are not skipped, then they will play wrong file.
This was tested on "Blue's Clues : Blue's Big Musical" and it fixed the missing audio there.
Taxi 2 is also said to be affected by this.
=> CDROM: Ignore sectors with channel number 255

libpcsxcore/new_dynarec/new_dynarec.c, libpcsxcore/psxhle.c, libpcsxcore/psxhle.h, libpcsxcore/psxinterpreter.c
Fix is from PCSX-redux :
https://github.com/grumpycoders/pcsx-redux/commit/99c9508f2a9dc1444b88f37eb100cdfb17862b52
This should hopefully fix HDHOSHY's experimental patch properly.
I'm not so sure about my code for the dynarec however but it is a direct equivalent to the interpreter's.
One instance when this does happen is Nuclear Strike over HLE when attempting to load a save.
```
#0  0x0000555555595e55 in psxBranchNoDelay ()
at libpcsxcore/psxinterpreter.c:293
#1  0x00005555555962c9 in psxDelayBranchTest (tar1=160)
at libpcsxcore/psxinterpreter.c:369
#2  0x0000555555596386 in doBranch (tar=160)
at libpcsxcore/psxinterpreter.c:419
#3  0x00005555555977b4 in psxJR () at libpcsxcore/psxinterpreter.c:629
#4  0x00005555555981c2 in psxSPECIAL () at libpcsxcore/psxinterpreter.c:824
#5 …
```
=> Properly protect the HLE instructions against corrupted memory.

libpcsxcore/cdriso.c, libpcsxcore/cdrom.c, libpcsxcore/plugins.h
There's a game, PoPoLoCrois Monogatari II, that unfortunately locks up during the intro screen.
I should have known that code was wrong as Mednafen did not have anything like that in their code either, hence the confusion.
Their fix however still don't include the Driver fix so the game would still crash if we don't have the "+ Seektime".
To be honest, i'm not sure why the PCSX Reloaded team did it this way...
In any case, i adjusted it so it doesn't mess up the audio for Driver's titlescreen and doesn't crash in Worms Pinball either.
Seems like setting it to 100000 was not enough for that game.
I noticed the fastword and FastBackward were not being used in any way.
Looked at Mednafen and all they do is just adjust the cursector
and make sure that fastword & backword trigger the …
=> Merge several fixes from PCSX Redux and adjust delay for SetLocPending.

libpcsxcore/cdrom.c
These fixes aim to address the inaccuracies of some CDROM commands and make it on par with nocash's doc and mednafen.
So far, it mostly fixes some delay issues in the Simple 1500 sound novel game as well as F1 2000 (which is notoriously time sensitive).
Notaz reviewed my PRs and he accepted all of them :
https://github.com/notaz/pcsx_rearmed/pull/209
https://github.com/notaz/pcsx_rearmed/pull/204
https://github.com/notaz/pcsx_rearmed/pull/203
https://github.com/notaz/pcsx_rearmed/pull/202
https://github.com/notaz/pcsx_rearmed/pull/201
https://github.com/notaz/pcsx_rearmed/pull/199
=> Various CDROM fixes from Duckstation and Mednafen

libpcsxcore/psxhw.c
For some reason, the game detects that a link cable is plugged in and disables the local multiplayer as a result.
Thanks @sony for fixing the issue in their PS Classic branch, a simpler fix is done here instead.
Closes https://github.com/libretro/pcsx_rearmed/issues/209
Here are screenshots for reference.
**Unfixed**
**Fixed**
=> Fix for Armored Core misdetecting a Link cable being detected

libpcsxcore/cdriso.c, libpcsxcore/cdrom.c, libpcsxcore/cdrom.h, libpcsxcore/plugins.h
This is taken from the way Mednafen implemented it.
https://github.com/libretro-mirrors/mednafen-git/blob/563b72e377fa8284559df4df0271108d4935c9f1/src/psx/cdc.cpp#L941
This properly fixes the freeze issue in Fantastic Pinball Kyuutenkai.
This will close https://github.com/libretro/pcsx_rearmed/issues/447 and https://github.com/libretro/pcsx_rearmed/issues/229.
The only fix i need help with is for the big endian specific code. I believe it doesn't need to be swapped in that case but i could be wrong...
=> Implement fix from Mednafen for Fantastic Pinball Kyuutenkai.

Makefile, Makefile.libretro, frontend/libretro.c, frontend/libretro_core_options.h, frontend/libretro_core_options_intl.h, frontend/main.c, frontend/menu.c, libpcsxcore/lightrec/plugin.c, libpcsxcore/new_dynarec/backends/psx/emu_if.c, libpcsxcore/plugins.c, libpcsxcore/psxbios.c, libpcsxcore/psxcommon.h, libpcsxcore/psxhw.c.orig, libpcsxcore/psxinterpreter.c, libpcsxcore/psxinterpreter.c.orig, libpcsxcore/psxmem.c, libpcsxcore/r3000a.c, libpcsxcore/r3000a.h
See (Redux) :
https://github.com/grumpycoders/pcsx-redux/commit/1923ce54ef585beba3a948d50f8c30161102312c
See original icache implementation (mirror of PCSX Reloaded):
https://github.com/gameblabla/pcsxr/commit/6916151e83dc99e7c9439d1d88492af8c873ef10
Known games to be affected by the lack of or improper ICache emulation :
- Formula F1 99
- Formula F1 2000 (EA)
- Formula One Champion Season 2000
- Formula One Arcade
- Formula F1 2001 (Confirmed to be fixed)
- Buster Bros. Collection
- ISS Pro 98
Buster Bros. Collection and ISS Pro 98 (PAL) are said to be affected by it (at least on other emulators with a dynarec) but they still work without ICache emulation at least on the interpreter.
Tested games :
* F1 2001 works but only through pure interpreter
* F1 Arcade will boot on interpreter but …
=> ICache emulation (Interpreter) from PCSX redux

libpcsxcore/new_dynarec/arm/assem_arm.c
According to neonloop himself
```
Literals are deduplicated, so there's no guarantee they will be stored
next to each other, even if they're written sequentially. verify_dirty
and get_bounds must use the offsets on each instruction, instead of
assuming values are stored sequentially.
```
According to him, this fixes a dynarec crash in FF7 on ARMv5 platforms like the F1C200S as used in the TrimUi handheld.
Given that the old3DS is ARMv6, it may also possibly fix some crashes there as well.
He granted me the permission to do a PR on his behalf. (he doesn't have a github account)
It seems that there might be a performance penalty for merging this... i wonder if there's another way.
Notaz approved the PR https://github.com/notaz/pcsx_rearmed/pull/194.
Worst case, if there are regressions, we …
=> Always look up verify_dirty literals from offsets by neonloop

libpcsxcore/cdrom.c
So far, i could only find Simple 1500 Series Vol. 31 - The Sound Novel to be affected by this.
In Duckstation, this was causing extra delays without it.
However in our case, this doesn't seem to be the case and i couldn't find much find about it.
=> Move CdlSetLoc to CdrInterrupt and return invalid arg error

libpcsxcore/cdrom.c
This was added back in 2013 or so in PCSX Rearmed.
According to some tests against Tomb Raider 1 (which is affected by the GetLocP code), it works properly without this hack.
So let's just remove it as we are now doing it properly.
Notaz also forgot the reason why he introduced the hack in the first place, see :
https://github.com/notaz/pcsx_rearmed/pull/235#issuecomment-955026232
=> Remove CdlGetLocP hack

libpcsxcore/psxcounters.c
As done by Duckstation
https://github.com/stenzek/duckstation/blob/bbcf1c67d1aefd5de9cdc9c158f92bc7aaecaa63/src/core/gpu.h#L56
It was also merged upstream. This is based on nocash's documentation (and several other emulations) stating that for PAL, it should be 314 due to the additional odd line.
=> One more on odd lines for PAL HSYNC

libpcsxcore/psxmem.c
This is related to the Tetris with Card Captor fix a while back.
However, i forgot to merge this one as well related to writes, even though it was not really necessary to fix that particular game.
This does not apply for ARM platforms, which use the dynarec.
=> psxmem: Writes to PIO Expansion area have no effect.

libpcsxcore/lightrec/plugin.c
Boost performance by running the dynarec until the next scheduled interrupt, instead of exiting after each compiled block.
=> Unlock Lightrec to its full potential

libpcsxcore/cdrom.c
Ooops, looks like i made a mistake :P
https://github.com/CometHunter92/pcsx_rearmed/commit/242b473df8b88101a013b639604b06d4418fad47
I didn't even notice this upon until someone reported it to me. It was working in redux when i merged it but i didn't do so for Rearmed... :<
=> Fix typo for DOA pause resume fix.

.gitlab-ci.yml, Makefile.libretro, frontend/libretro_core_options.h
Build for Miyoo which has the same ARM926EJ-S CPU as the Wiz/Caanoo
platforms so use similar build flags.
Enable hi-res downscaling by default for the UNAI GPU renderer to scale
to the device's 320x240 screen.
=> platforms: Add Miyoo target

frontend/libretro_core_options.h
Disable reverb and interpolation for pre-ARMv7 CPUs to match
emu_set_default_config(). Affects the ARMv5TEJ Miyoo and ARMv6 3DS and
Raspberry Pi 1.
=> Fix SPU defaults for pre-ARMv7 CPUs

frontend/libretro.c, frontend/libretro_core_options.h, frontend/plugin_lib.h, plugins/gpulib/gpu.c, plugins/gpulib/gpu.h
The change uses same style as other cores with auto frameskip. PSX doesn't always render every frame, so skipped frames that wouldn't have been rendered aren't used for frameskip limit.
=> Adds auto frameskip based on free audio buffer space

frontend/libretro.c, frontend/libretro_core_options.h, frontend/main.c
Follows newer frameskip code from snes9x2002 and fixes fixed_interval frameskip when audio driver doesn't support buffer monitoring. 
Changes default interval to 3, this setting also controls maximum autoframeskip so default of 1 is too low. From reports, people and games have different tolerance for audio or video stuttering and this allows adjusting
Also disables iTempo for Miyoo builds, this setting only has correct effect in standalone and generates too much audio every frame in RetroArch.
=> Updates auto-frameskip

frontend/main.c
Leave iTempo set to 0 on all libbretro platforms. This fixes the build
failure for Miyoo. Also results in iTempo being 0 for Raspberry Pi 1,
which is faster than the Miyoo but slower than the new 3DS.
Fixes the CI failure for Miyoo in #636.
=> frontend: Disable iTempo

frontend/libretro.c, frontend/libretro_core_options.h
fixes core options getting crazy if coming from a previous core version;
plus a little bit of cleaning and <s>reverting to "frameskip interval = 1" as default, as a value of "3" is too high<s>
=> fixes and cleaning

libpcsxcore/lightrec/plugin.c, libpcsxcore/misc.c, libpcsxcore/r3000a.h
To create save states the psxRegs variable must be up-to-date. Therefore
we need to store back all the registers in Lightrec's cache into psxRegs
before saving, and reload them into Lightrec's cache after loading a
save state.
=> lightrec: Fix save states

deps/lightning/.gitrepo, deps/lightning/check/Makefile.am, deps/lightning/check/lightning.c, deps/lightning/lib/jit_aarch64-cpu.c, deps/lightning/lib/jit_aarch64-sz.c, deps/lightning/lib/jit_aarch64.c, deps/lightning/lib/jit_arm-cpu.c, deps/lightning/lib/jit_arm-sz.c, deps/lightning/lib/jit_arm.c, deps/lightning/lib/jit_ppc-cpu.c, deps/lightning/lib/jit_ppc-sz.c, deps/lightning/lib/jit_ppc.c, libpcsxcore/misc.c
- Sync GNU Lightning to the latest version from my repository. It adds implementations of conditional opcodes on ARM (+thumb2), Aarch64 and PowerPC.
- Add a fix to the previous "fix savestates" PR. Synchronizing Lightrec's register cache into PCSX' psxRegs variable must
be done only if using Lightrec, not when using PCSX' interpreter.
=> Update lightrec 20220427

frontend/libretro.c, frontend/libretro_core_options.h, frontend/libretro_core_options_intl.h, libretro-common/include/libretro.h
This PR updates the core options to v2 format. In addition:
- Core option categories have been added
- On frontends without category support, the various 'show/hide input/GPU plugin settings' options now apply in real time (without togging the quick menu)
- Missing option sublabels have been added
- Existing sublables have been clarified
- Options have been generally reordered/reorganised in more rational fashion...
- Three non-functional (and confusing) options have been removed: `pcsx_rearmed_gpu_peops_old_frame_skip`, `pcsx_rearmed_gpu_unai_ilace_force`, `pcsx_rearmed_gpu_unai_pixel_skip`
=> Update core options to v2 format

Makefile, Makefile.libretro, libpcsxcore/cdrom.c, libpcsxcore/lightrec/mem.c, libpcsxcore/lightrec/mem.h, libpcsxcore/lightrec/plugin.c, libpcsxcore/misc.c, libpcsxcore/psxbios.c, libpcsxcore/psxdma.c, libpcsxcore/psxinterpreter.c, libpcsxcore/psxmem.c, libpcsxcore/psxmem.h, libpcsxcore/r3000a.c
Lightrec can greatly benefit from having the RAM/BIOS/scratchpad and RAM mirrors mapped to specific addresses. For the same value of `offset`:
- If the RAM is mapped to `offset`, the BIOS is mapped to  `offset + 0x1fc00000` and the scratchpad to `offset + 0x1f800000`, the generated code will be better;
- If the RAM is also mirrored to `offset + 0x200000`, `offset + 0x400000` and `offset + 0x600000`, the generated code will be even better;
- If `offset` is 0x0, the generated code will be even better.
Supporting mapping emulated RAM to address 0x0 requires a few changes, since a pointer whose value is 0x0 will be detected as a NULL pointer. The read/write LUTs are now initialized with 0xff, and all pointers are now checked against a new `INVALID_PTR` macro.
Note that mapping the RAM to 0x0 …
=> Lightrec: Make memory map as perfect as possible

Makefile, libpcsxcore/lightrec/mem.c
Some distributions of Linux don't have the MFD_HUGETLB flag in
<linux/memfd.h>, probably because their kernel headers installed are too
old. In that case, we locally define MFD_HUGETLB to the value it should
have.
On Windows, the HAVE_MMAP macro set for GNU Lightning was also used in
libretro-common/vfs/vfs_implementation.c, causing build issues. Address
this problem by only defining HAVE_MMAP for Lightning source files.
=> Fix Lightrec build on Windows and Linux

deps/lightning/.gitrepo, deps/lightning/lib/jit_size.c
Update GNU Lightning to the latest version on my repo, to get this fix: https://github.com/pcercuei/gnu_lightning/commit/7fce9abb2a6bfc3967b4e5705794e617ed909402
Without it, the code buffer will start overflowing after maybe 1.5 MiB of generated code, even though the code buffer is 8 MiB.
=> Update GNU Lightning

libpcsxcore/plugins.c
Noticed that in some games the controller will rumble even if 'standard' is selected as a device type. It's happening in Resident Evil - Director's Cut - Dual Shock Ver. when you shoot or push an object for example, I also noticed it when your health is low in Silent Hill.
Even the rumble core option says it should only work with 'dualshock' device type: https://github.com/libretro/pcsx_rearmed/blob/9723f27f9d28d90c8f54a9cd9e7203a87cc41b29/frontend/libretro_core_options.h#L769
So here's a little fix, idk if there's a better way to handle that but it seems to work properly.
=> Rumble should only work with 'dualshock' device type

frontend/cspace.c, libpcsxcore/cdriso.c, libpcsxcore/gpu.h, libpcsxcore/misc.c, libpcsxcore/psxcounters.c, libpcsxcore/psxdma.c, libpcsxcore/psxhw.c, libpcsxcore/psxmem.h, libpcsxcore/r3000a.h, plugins/dfxvideo/draw.c, plugins/dfxvideo/gpu.c, plugins/dfxvideo/gpu.h, plugins/dfxvideo/gpulib_if.c, plugins/dfxvideo/prim.c, plugins/dfxvideo/soft.c, plugins/gpulib/gpu.c, plugins/gpulib/gpu.h, plugins/gpulib/vout_pl.c
Equivalent to https://github.com/notaz/pcsx_rearmed/pull/142, but without the CI/buildscript changes that don't apply to libretro.
Hard work done by @pcercuei, I'm just PRing it.
Original description: 
> A couple of fixes to the PCSX core to make it able to run on big-endian systems.
Tested on 32-bit PPC.
> 
> The various GPU plugins would also need to be patched in order to access the VRAM properly.
=> Fix PCSX core and dfxvideo for big-endian systems

libpcsxcore/lightrec/mem.c, libpcsxcore/psxmem.c
The BIOS was mapped as 2 MiB, since we want to use a huge page if
possible. Therefore it should also be unmapped as 2 MiB, otherwise the
upper 1.5 MiB will still be mapped after de-init, which will make it
impossible to map the BIOS once again.
Fixes #667.
=> lightrec: Fix unmap size of BIOS

deps/lightrec/.gitrepo, deps/lightrec/disassembler.c, deps/lightrec/disassembler.h, deps/lightrec/emitter.c, deps/lightrec/interpreter.c, deps/lightrec/lightrec-private.h, deps/lightrec/lightrec.c, deps/lightrec/optimizer.c, deps/lightrec/regcache.c, deps/lightrec/regcache.h, libpcsxcore/lightrec/plugin.c
When a dynarec plugin reset is requested, Lightrec will simply invalidate all emitted code and reset the registers to the default values, instead of destroying the existing instance to create a new one.
Bump Lightrec to the latest upstream version, which has seen quite a few changes, that should improve performance by a noticeable margin.
=> Update lightrec 20220716

deps/lightrec/.gitrepo, deps/lightrec/optimizer.c, libpcsxcore/lightrec/plugin.c
Small fixes:
- Fix crash in Sled Storm during / after the intro FMV
- Fix the lights on the monkeys in Ape's Escape
=> Update lightrec 20220912

jni/Android.mk
Android builds don't use the Makefile, and the build recipe wasn't modified to add the new constprop.c source file from Lightrec.
=> Fix Android build

frontend/libretro.c, libpcsxcore/plugins.c
Some background discussion on the issue I try to solve with this is in #655.
The short explanation is that manually scaling/shifting the GunCon coordinates via the core options will often shrink the amount of space usable by a lightgun device due to the way the emulator sets strict bounds for the gun coordinates. These suggested changes open up the range of values and redefine what "offscreen" means in terms of the Libretro API instead of the original fixed range of values.
I initially tried to do this:
I wanted to adapt the coordinate formulas from page 162 of [this document](https://static.grumpycoder.net/pixel/document.pdf) to hopefully eliminate the need for manual scaling via the core options, but I kept running into inconsistencies. There appear to be three possible ways that games …
=> Expand usable space for GunCon

Makefile
Untested, but this should work.
GNU Lightning does use the 'HAVE_MMAP' macro, so it needs to be defined when compiling it; otherwise Lightning will fail on an assert() at runtime.
=> Fix Win32 build, part 2

Makefile, Makefile.libretro, libpcsxcore/lightrec/sysconf.c
Add the missing sysconf() function so that the GC/Wii builds will link properly against Lightrec and GNU Lightning.
Note that the actual page size returned doesn't really matter - it is used by Lightning to align the size of code blocks to be flushed with GCC's __clear_cache, which is a NOP on the GC/Wii.
=> make: Enable Lightrec for GC/Wii

libpcsxcore/lightrec/mem.c, libpcsxcore/lightrec/mem_wiiu.c, libpcsxcore/lightrec/plugin.c
Provide Lightrec with a code buffer even when using a non-custom memory map, as some platforms (NGC, Wii) cannot emit code outside a provided code buffer.
=> lightrec: Alloc code buffer with standard memory map

libpcsxcore/lightrec/mem.h
Allow the CODE_BUFFER_SIZE macro to be overriden.
This is helpful on platforms that don't want a 8 MiB buffer.
=> lightrec: Allow to override code buffer size

Makefile.libretro, frontend/plugin.c
* JIT recompiler isn't available for this platform, setting `DYNAREC` to nothing forces the interpreter mode.
* WASM raises "null function or function signature mismatch" when calling a fallback function like `dummy_func`, I replaced it by actual dummy implementations.
=> Fix emscripten build

plugins/gpu_unai/gpu_command.h, plugins/gpu_unai/gpu_inner.h, plugins/gpu_unai/gpu_inner_quantization.h, plugins/gpu_unai/gpu_raster_image.h, plugins/gpu_unai/gpu_raster_line.h, plugins/gpu_unai/gpu_raster_polygon.h, plugins/gpu_unai/gpu_raster_sprite.h, plugins/gpu_unai/gpu_unai.h, plugins/gpu_unai/gpulib_if.cpp
Fix VRAM and PacketBuffer accesses to always go through endianness conversion. This should fix most of Unai on big-endian systems.
I think it is not 100% complete as RGB888 frames are still rendered in the host's endian - but in my case the emulator (WiiSX) expects a host endian format for RGB888 so it still works.
=> unai: Add support for big-endian

libpcsxcore/database.c, libpcsxcore/lightrec/plugin.c
And add entries for the infamous Formula One games.
These games do tricks with the instruction cache that are hard to emulate properly in an interpreter, and almost impossible in a dynamic recompiler.
Funnily enough, emulating the CPU less accurately by only invalidating cached code on DMA writes and never on CPU writes make these games work.
These hacks will also make Lightrec generate faster code, but they are unsafe by nature, and that's why they are conditionally enabled.
=> libpcsxcore: Add database for Lightrec hacks

libpcsxcore/lightrec/plugin.c
Lightrec is only initialized once, when the emulator starts. We need to set the unsafe flags after reset because the setting will be different across games.
=> libpcsxcore: Set unsafe flags after reset

plugins/gpu_unai/gpu_unai.h, plugins/gpu_unai/gpulib_if.cpp
Both the VRAM and the downscale buffers are in little-endian format, there's no need to do any endianness conversion.
=> unai: Fix scalers doing endianness conversion

libpcsxcore/lightrec/plugin.c
Some games (F1 2000, maybe others) require BREAK to be emulated properly.
=> lightrec: Emulate BREAK

frontend/libretro.c
To match the #if from libretro_core_options.h: https://github.com/libretro/pcsx_rearmed/blob/81574accf59f445626568ec6b4388d887ddc8595/frontend/libretro_core_options.h#L798-L813
so it silences this error every time the core checks core options:
> [ERROR] [Environ]: GET_VARIABLE: pcsx_rearmed_spu_thread - Invalid value.
=> Add missing #if for the "Threaded SPU" core option

plugins/gpu_unai/gpu_inner.h, plugins/gpu_unai/gpu_inner_light.h, plugins/gpu_unai/gpu_unai.h
Use a new 'gcol_t' type which fits in 64 bits, and encode each color component into a 8.8 fixed-point format.
This boosts the precision of the gouraud shading algorithm, at almost zero cost.
Fixes #320.
=> unai: Use 8.8 RGB triplet format for gouraud shading

Makefile, frontend/menu.c
Enable GCC's (or LLVM's) Address Sanitizer when DEBUG=1 is set.
As it says in the commit message, this is not available everywhere, so if you think it's a problem I can enable it through a "DEBUG_ASAN" variable or something like that.
It detects a lot of problems, one of which I fixed in Lightrec in PR #801, another one in the frontend that I fixed here.
It detects other issues, notably in the SPU plugin (reproducible in Duke Nukem Total Meltdon, boot the game and leave it running until the emulator exits) that have yet to be fixed.
=> Address sanitizer

deps/lightrec/.gitrepo, deps/lightrec/lightrec.c
Update to latest Lightrec, which only has one commit since the last pull, but this commit fixes the last race in the threaded compiler.
I've been using it for hours now on PC (8 cores, so 7 compiler threads used) and it is been as stable as the single-core builds; I did not notice any difference in emulation.
Fixes https://github.com/libretro/pcsx_rearmed/issues/697.
=> Update to Lightrec 2023-11-20, fix the threaded compiler

deps/lightrec/.gitrepo, deps/lightrec/interpreter.c
Should fix #782 and maybe other games. Lightrec was sometimes returning from exceptions one opcode before the actual target, which potentially caused all kind of nasty effects in affected games; e.g. missing polygons in Colin Mc Rae Rally and Vagrant Story, and crashes in Um Jammer Lammy.
=> Update Lightrec 2023-11-24

libpcsxcore/lightrec/plugin.c
Invalidate the whole code buffer on each call to the .clear callback. This fixes a crash after finishing a race in F1 Arcade, and does not seem to cause issues with the other F1 games.
Fixes #788.
=> lightrec: Improve hack around icache emulation

Makefile.libretro, frontend/main.c
Emscripten 3.1.53 causes attempted cpu checks to now fail with "unsupported platform"
Enables `NO_MMAP` and `NO_PTHREAD`
=> Fix emscripten build target

libpcsxcore/database.c
Decrease it from 175 to 174, which is enough for the language selection menu to start working.
=> db: Override cycle multiplier for Colin McRae PAL

include/lightning/lightning.h
This had not been done the last time the Lightning subrepo was pulled.
Fixes #825.
=> lightning.h: Bump to latest version

libpcsxcore/cdrom.c
"stat" is a C function from <sys/stat.h>. While libpcsxcore/cdrom.c does not include this header, some of the headers it does include may actually include it themselves (depending on the C library).
Work around possible name conflicts by just renaming the offending variable.
=> cdrom: Rename "stat" to "cdr_stat"

deps/lightrec/.gitrepo, deps/lightrec/CMakeLists.txt, deps/lightrec/arch.h, deps/lightrec/emitter.c, deps/lightrec/lightning-wrapper.h, deps/lightrec/lightrec-config.h.cmakein, deps/lightrec/lightrec-private.h, deps/lightrec/lightrec.c, deps/lightrec/optimizer.c, deps/lightrec/regcache.h, include/lightrec/lightrec-config.h
Fixes #838.
Also added a tiny optimization where high masks (bits 31->x set) or low masks (bits x->0 set) are applied directly on selected archs instead of being loaded into a register first.
=> Update lightrec 20240715

Makefile.libretro
Build was failing on Haiku due to cdrom.c in libretro-common, force-disabling CD-ROM code is simplest way to restore Haiku build (until Haiku-specific code is added to libretro-common, eventually)
=> Restore Haiku build

Makefile.libretro
Now that we can support threads in emscripten, this Makefile should be modified.
I ran into duplicate symbol problems when compiling PCSX's thread support, so I had to disable threads within the emulator to avoid duplicates of rthread.o.  I'd appreciate advice in general on working with cores that could have threading support and including libretro-common under static linking scenarios (since retroarch also includes libretro-common).
=> Fixes to libretro makefile for emscripten builds
