libretro/pcsx_rearmed

frontend/libretro.c

Expose already existing hacks that allow to run games that have timing
issues.

Expose 2 game hacks to allow play PE2, VH1/2 & Inuyasha

---

configure
frontend/libretro.c
frontend/main.c
frontend/menu.c
include/arm_features.h
libpcsxcore/cdriso.c
libpcsxcore/cdrom.c
libpcsxcore/new_dynarec/linkage_arm.S
libpcsxcore/r3000a.h
plugins/dfsound/arm_utils.S
plugins/dfsound/spu.c
plugins/gpu_unai/gpulib_if.cpp

Tested on Raspberry Pi 3 - Arm flag changes are working properly. Haven't tested large file support but can't see any regression.

Merging in latest upstream changes

---

Makefile.libretro

Sorry I forgot to add the ASFLAGS line in the last pull request

Add ASFLAGS for rpi2 platform

---

Makefile
include/psemu_plugin_defs.h
libpcsxcore/plugins.c
plugins/dfinput/main.c
plugins/dfinput/pad.c

Add rumble feature for controller 1 and 2.
Add support of dual shock protocol to declare rumble/analog mode for controller correctly like Sony protocol implementation.
Fix lag on analog controller.
Refactor some code.

add rumble support for controler 1 and 2 

---

frontend/libretro.c

Split update_controller_port_device() into
update_controller_port_variable() updating the controllers from the
variables, update_controller_port_device() updating the controllers from
retro_set_controller_port_device() and controller_port_variable()
sharing getting the controller variable between the two.
Avoid setting to PSE_PAD_TYPE_NONE controllers whose variable is set to
'default' when updating them.

libretro: Split update_controller_port_device()

---

frontend/libretro.c

Reverts libretro/pcsx_rearmed#97

Revert "return false if info is NULL inside retro_load_game"

---

Makefile.libretro
frontend/3ds/sys/mman.h

Fixes for 3DS

---

.gitmodules

The paths were removed in 76e889bcfaf9776b071627e7e8c9bff0465f539c.

Remove the git submodules

---

frontend/libretro.c

If you have multiple BIOS files available for use, search for the newest version first (I find the newer BIOSes tend to work better).

Search for the newest version of the BIOS first

---

frontend/libretro.c

Spelling out this error message to make even more obvious.

Another minor update to no BIOS error string

---

Makefile.libretro
frontend/cspace.c

Fixed building for arm64 (iOS)

---

Makefile.libretro
frontend/cspace.c

Reverts libretro/pcsx_rearmed#144

Revert "Fixed building for arm64 (iOS)"

---

Makefile.libretro
frontend/cspace.c

now tested building for ios, ios9 and ios-arm64 all compiling again.
Have ran arm64 version, however unable to test others.

iOS Compilation Updates

---

Makefile.libretro

This one required probably the least tweaking to build in Solaris so far. It's ridiculous :D

PCSX Rearmed Solaris core

---

frontend/libretro.c

Fixed value to match setting and removed hard-coded config value.

Fix region core option. 

---

frontend/libretro.c

The current neGcon implementation maps the analog I/II buttons to the RetroPad R2/L2 inputs. This is the optimal setup for a 'modern' control scheme when using a gamepad with analog triggers, but a friend recently complained that most popular Android gamepads (e.g. the 8bitdo family, and all iPegas) only have digital triggers - so half the neGcon functionality is lost.
This pull request tries to solve the issue by additionally mapping the I/II buttons to the RetroPad right analog stick. It's not as elegant as using proper triggers, but it allows for a 'conventional' up/down acceleration/braking scheme of the type found in most DualShock-compatible racing games.

[NeGcon] Add mapping of analog I/II buttons to right analog stick

---

Makefile.libretro

related: https://github.com/libretro/libretro-super/issues/976

[ios] Try to fix build target mixups

---

Makefile.libretro

Fix OSX interpreter build target

---

libpcsxcore/plugins.c

- Tested with KoroKoro Post Nin - no input in whatever combination of inputs used
- Tested with Legend of Mana - cannot skip FMV using gamepad
Fix: https://github.com/libretro/pcsx_rearmed/issues/161

Fix input not working in some games

---

libpcsxcore/gte.c

fix https://github.com/libretro/pcsx_rearmed/issues/216

Sync gte fixes from upstream

---

jni/Android.mk

Add CHD support for Android

---

Makefile.libretro

Quick change to add support for rpi4 platform

Add support for rpi4 platform with cortex-a72 cpu

---

libpcsxcore/psxbios.c

reference: https://github.com/libretro/pcsx_rearmed/issues/316

HLE BIOS improvements from upstream

---

Makefile.libretro

It now builds properly, and is much much faster.

Re-enable unai on 3DS

---

Makefile
deps/lightning/lib/jit_memory.c
deps/lightning/lib/lightning.c

Fix Linux build

---

libpcsxcore/lightrec/plugin.c
libpcsxcore/misc.c

Fixes #382 again, due to the previous attempt breaking reset.

Fix second instance runahead without breaking reset

---

frontend/libretro_core_options.h

Have dithering disabled by default on 3DS.

(3DS) Disable dithering by default

---

deps/libchdr/bitstream.c
deps/libchdr/bitstream.h
deps/libchdr/cdrom.c
deps/libchdr/cdrom.h
deps/libchdr/chd.c
deps/libchdr/chd.h
deps/libchdr/coretypes.h
deps/libchdr/flac.c
deps/libchdr/flac.h
deps/libchdr/huffman.c
deps/libchdr/huffman.h

Update libchdr based from latest upstream sources. Fixes some issues as noted.
- Latest upstream commit: https://github.com/rtissera/libchdr/tree/6117d59d00ef8620de4cff4d6ecae46368cae881
- Fix https://github.com/libretro/pcsx_rearmed/issues/301
- Specific commit that fixes above problem: https://github.com/rtissera/libchdr/commit/e1acac6d83b36531e543e39a9e1a363e681083e6

libchdr: Update to latest upstream

---

deps/lightrec/.gitrepo
deps/lightrec/recompiler.c

lightrec: fix race that could cause a freeze during load/reset

---

libpcsxcore/cdriso.c

Enables parsing of `.cd<X>` files as cuesheets.
Useful to hide individual `.cue` files from the frontend
when using a multi-disc game configured in a playlist (`.m3u`) file.
This is a front-end related change, for game launchers that rely on the file extension
to detect and display games. I.e. when having a multi-disc games organized as `.m3u`,
it's useful to rename the `.cue` files to `.cd1`, `.cd2`, etc and use an `.m3u` with
```
Disc_1_of_2.cd1
Disc_2_of2.cd2
```
instead of
```
Disc_1_of_2.cue
Disc_2_of_2.cue
```
The front-end ignores the `.cd<X>` files and they will not show up in the list.

cdriso: parse .cd<X> files as .cue

---

deps/libchdr/chd.c
deps/libchdr/coretypes.h
deps/libchdr/huffman.c

Based on commit https://github.com/rtissera/libchdr/tree/16759edf50f39ecea7bfe8564d689fa01e0fae0c
but without directory stucture and filename changes.

Update libchdr from latest upstream changes

---

plugins/gpulib/gpulib_thread_if.c

When DMA requests force a background queue flush, the update lace handler can no longer know there was a pending frame. If this happens often enough, it can delay the next frame indefinitely.
Whenever the background queue is emptied, the next update_lace needs to force a render.

Fix unnecessary threaded rendering frame drops

---

Makefile
frontend/libretro.c
libpcsxcore/plugins.c

remove dfinput, fix negcon input

---

libpcsxcore/cdriso.c

fix chd track info parsing.

---

frontend/libretro.c
frontend/libretro_core_options.h
libpcsxcore/cdriso.c
libpcsxcore/psxcommon.h

reference: https://github.com/libretro/pcsx_rearmed/issues/261

CHD: Support for precache mode CD access method

---

deps/libchdr/coretypes.h

Signed-off-by: Bartłomiej Burdukiewicz <bartlomiej.burdukiewicz@gmail.com>

Removed conditional include on non-existent file.

---

libpcsxcore/new_dynarec/backends/psx/emu_if.h
libpcsxcore/new_dynarec/new_dynarec.c

I accidentally broke it so this fixes the compilation errors when compiling the ARM dynarec.
Next time i do a potentially code breaking change, i'll push it to the staging branch.
My bad

Fix broken HLE PR

---

libpcsxcore/cdrom.c
libpcsxcore/cdrom.h

Per feedback from notaz, thanks to him.

Revert some changes as they were not tested or are not required

---

Makefile.libretro

Add a target to build AArch64 build of this core on rpi3 making use of lightrec CPU core and unai GPU core

Add Raspberry Pi 3 64-bit target

---

Makefile
include/lightning/lightning.h

This should fix building on the CI.

Add missing lightning.h include file

---

deps/lightrec/.gitrepo
deps/lightrec/lightrec.c

Fixes a bug that causes a crash very early.
It's the last PR today, I swear ;)

Update to latest Lightrec

---

frontend/libretro.c
frontend/libretro_core_options.h
frontend/plugin_lib.h
plugins/gpulib/gpu.c
plugins/gpulib/gpu.h

Reverts libretro/pcsx_rearmed#631

Revert "Adds auto frameskip based on free audio buffer space"

---

frontend/libretro.c
frontend/libretro_core_options.h
frontend/plugin_lib.h
plugins/gpulib/gpu.c
plugins/gpulib/gpu.h

Reverts libretro/pcsx_rearmed#633

Revert "Revert "Adds auto frameskip based on free audio buffer space""

---

frontend/libretro.c

-Add Trigger, Reload, Aux A, and Aux B as mappable buttons in RetroArch menu for players 1 and 2.
-GunCon trigger, A, and B buttons are mapped to Gun Trigger, Gun Aux A, and Gun Aux B instead of hard coded to left click, right click, and middle click.
-Force cursor to corner of screen for offscreen reload so that reloading works on all four edges of the screen.
-Allow Gun Reload RetroArch input to emulate an offscreen shot.
-Switch gun coordinates from "Pointer" type to "Lightgun" type.

GunCon overhaul

---

deps/lightrec/.gitrepo
deps/lightrec/recompiler.c

Latest version fixes crashes reported in #626.

Update Lightrec to version 2022.04.09

---

deps/lightrec/.gitrepo
deps/lightrec/emitter.c
deps/lightrec/lightrec-private.h
deps/lightrec/lightrec.c
deps/lightrec/recompiler.c
frontend/cspace.c
plugins/gpu_neon/psx_gpu_if.c
plugins/gpu_unai/gpulib_if.cpp
plugins/gpulib/vout_sdl.c

Remove duplicated code, and update Lightrec to the latest master, which fixes #664.

Update lightrec 20220607

---

Makefile
deps/lightrec/.gitrepo
deps/lightrec/emitter.c
deps/lightrec/lightrec.c
include/mman/sys/mman.h
libpcsxcore/lightrec/plugin.c

Small bugfix of the previous update.

Update lightrec 20220911

---

deps/lightrec/.gitrepo
deps/lightrec/emitter.c

Update to the latest Lightrec.
Fixes bugs affecting Jackie Chan Stuntmaster, Vib-Ribbon, GTA2, and maybe other games.

git subrepo pull --force deps/lightrec

---

Makefile
deps/lightrec/.gitrepo
deps/lightrec/CMakeLists.txt
deps/lightrec/constprop.c
deps/lightrec/constprop.h
deps/lightrec/disassembler.c
deps/lightrec/emitter.c
deps/lightrec/interpreter.c
deps/lightrec/lightrec-private.h
deps/lightrec/lightrec.c
deps/lightrec/lightrec.h
deps/lightrec/optimizer.c
deps/lightrec/optimizer.h
deps/lightrec/regcache.c
deps/lightrec/regcache.h

Update Lightrec 2023-02-08

---

deps/lightrec/.gitrepo
deps/lightrec/emitter.c
deps/lightrec/optimizer.c

Fixes a few games that got broken recently because of unwanted side effects of an optimization.
(FF8, Jumping Flash 2, Xenogears).

Update to latest Lightrec 2023-07-27

---

deps/lightrec/.gitrepo
deps/lightrec/disassembler.h
deps/lightrec/emitter.c
deps/lightrec/interpreter.c
deps/lightrec/lightrec.h

Add the necesary bits to support HLE.
Fixes #755.

Update Lightrec 2023-09-02

---

deps/lightrec/.gitrepo
deps/lightrec/blockcache.c
deps/lightrec/emitter.c
deps/lightrec/interpreter.c
deps/lightrec/lightrec-private.h
deps/lightrec/lightrec.c
deps/lightrec/optimizer.c
deps/lightrec/recompiler.c

Bump to latest Lightrec master, which fixed some games (among others: Gex 3, Yu-Gi-Oh, Twisted Metal 3).

Lightrec update 20230913

---

deps/lightrec/.gitrepo
deps/lightrec/emitter.c
libpcsxcore/psxmem.h

Fix an annoying warning + a nasty out-of-bounds buffer access.

Update lightrec 20231023

---

deps/lightrec/.gitrepo
deps/lightrec/lightrec.c
deps/lightrec/lightrec.h
libpcsxcore/lightrec/plugin.c

lightrec: Update prototypes of memory write callbacks

---

deps/lightning/.gitrepo
deps/lightning/include/lightning.h.in
deps/lightning/include/lightning/jit_private.h
deps/lightning/lib/jit_disasm.c
deps/lightning/lib/jit_print.c
deps/lightning/lib/lightning.c
deps/lightrec/.gitrepo
deps/lightrec/lightrec.c
deps/lightrec/optimizer.c

Just pull a fix for an out-of-buffer read from upstream Lightrec.

Update lightrec 20231119

---

deps/lightrec/.gitrepo
deps/lightrec/constprop.c
deps/lightrec/emitter.c
deps/lightrec/lightrec.c
deps/lightrec/regcache.c
deps/lightrec/regcache.h

Brings a fix for #843 + a few improvements to the code generation.

Update Lightrec 2024-09-02

---

deps/lightning/.gitrepo
deps/lightning/lib/lightning.c
deps/lightrec/.gitrepo
deps/lightrec/CMakeLists.txt
deps/lightrec/interpreter.c
deps/lightrec/optimizer.c

Bump Lightrec to the latest version, which fixes #861.

Update Lightrec 2025-01-08

---

deps/lightrec/.gitrepo
deps/lightrec/README.md
deps/lightrec/interpreter.c

Lightrec update 2025-01-12

---

deps/lightrec/.gitrepo
deps/lightrec/disassembler.c
deps/lightrec/disassembler.h
deps/lightrec/emitter.c
deps/lightrec/lightrec.c
deps/lightrec/optimizer.c
deps/lightrec/recompiler.c

Fixes https://github.com/libretro/pcsx_rearmed/issues/892.

Update Lightrec to latest git master (2025-08-15)
